name: Docker push container at org level (GITHUB_TOKEN)
on: push

permissions:
 packages: write

jobs:
 all:
  runs-on: ubuntu-latest
  
  steps:
   - name: Echo Github Actor
     run: echo ${{ github.actor }}
   - name: Echo Github Token
     run: echo ${{ secrets.GITHUB_TOKEN }}
   - name: Login to GitHub container Registry
     run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
   - name: Build the Docker image
     run: docker pull redis:latest
   - name: tag the Docker image
     run: docker tag redis:latest ghcr.io/aashijtestorg/redis:latest
   - name: Push the Docker image to the registry
     run: docker push ghcr.io/aashijtestorg/redis:latest
