name: Docker Push public container in org (without repo name)
on: push

permissions:
 packages: write

jobs:
 all:
  runs-on: ubuntu-latest
  
  steps:
   - name: Login to GitHub container Registry
     run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
   - name: Build the Docker image
     run: docker pull consul:latest
   - name: tag the Docker image
     run: docker tag nginx:latest ghcr.io/aashijtestorg/centauri/consul:latest
   - name: Push the Docker image to the registry
     run: docker push ghcr.io/aashijtestorg/centauri/consul:latest
